### ISSUE TITLE
Should we exclude or include pyproject.toml

### ISSUE THREAD

**Issue by kbakk** [camunda-community-hub/pyzeebe#183]
Each time I install using `pipenv install --dev` I get a `pyproject.toml` generated in the project:

```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"
```

I don't really understand where this is coming from. It seems to be setuptools related. It's only when running with `--dev` flag it's created. 

Should it be included or ignored?

Somewhat on the same topic, I think this project could benefit from changing from setup.py to pyproject.toml and flit/poetry. flit would only manage the packaging aspect of this project, while with poetry it would do that in addition to managing virtualenvironments and dev dependencies (i.e. replace pipenv).
