### ISSUE TITLE
pyzeebe Multi-Tenancy Issue

### ISSUE THREAD

**Issue by udaysd7897** [camunda-community-hub/pyzeebe#579]
**Describe the bug**
When using pyzeebe with multi-tenancy enabled, the tenant ID is not properly included in the gRPC request context. Even though the ZeebeWorker is configured with tenant_ids=['tenant1'], the Zeebe gateway rejects requests with the error: "Expected to handle gRPC request ActivateJobs with tenant identifier 'tenant1', but tenant could not be retrieved from the request context".

**To Reproduce**
1. Install camunda with the following helm values, Notice ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE is none
```
identityKeycloak:
    enabled: true
    postgresql:
        enabled: true
        auth:
            existingSecret: identity-secret-for-components
    auth:
        existingSecret: identity-secret-for-components


global:
    multitenancy:
        enabled: true
    elasticsearch:
        enabled: true
    opensearch:
        enabled: false

    identity:
        auth:
            # enabled: false
            publicIssuerUrl: http://localhost:18080/auth/realms/camunda-platform
            zeebe:
                existingSecret:
                    name: identity-secret-for-components
            connectors:
                existingSecret:
                    name: identity-secret-for-components
            operate:
                redirectUrl: http://localhost:8081
                existingSecret:
                    name: identity-secret-for-components
            tasklist:
                redirectUrl: http://localhost:8082
                existingSecret:
                    name: identity-secret-for-components
            optimize:
                redirectUrl: http://localhost:8083
                existingSecret:
                    name: identity-secret-for-components
            webModeler:
                redirectUrl: http://localhost:8084
            console:
                redirectUrl: http://localhost:8085
                existingSecret:
                    name: identity-secret-for-components

identity:
    enabled: true
    fullURL: http://localhost:8080
    resources:
      requests:
        cpu: "100m"     # Minimal request
        memory: "64Mi" # Minimal request

identityPostgresql:
  enabled: true
  auth:
    existingSecret: identity-secret-for-components
      
elasticsearch:
    enabled: true
    master:
        replicaCount: 1  # Ensure only one replica for Elasticsearch master
    resources:
      requests:
        cpu: "100m"         # Minimal request
        memory: "128Mi"    # Minimal for ES to start
           # Keep default limit

    persistence:
      size: 10Gi

zeebe:
  clusterSize: 1  # Ensure only one Zeebe broker
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
  resources:
    requests:
      cpu: "100m"     # Minimal request
      memory: "64Mi" # Minimal request


zeebeGateway:
  replicas: 1  # Ensure only one Zeebe Gateway replica
  env:
    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
      value: none
  resources:
    requests:
      cpu: "100m"      # Minimal request
      memory: "32Mi" # Minimal request


tasklist:
  enabled: true
  resources:
    requests:
      cpu: "100m"     # Minimal request
      memory: "64Mi" # Minimal request


operate:
  enabled: true
  resources:
    requests:
      cpu: "100m"     # Minimal request
      memory: "64Mi" # Minimal request

  

optimize:
    enabled: false

connectors:
    enabled: false
        

console:
  enabled: true

``` 
2. Initialize a Zeebe worker with `tenant_ids` parameter
3. Error occurs: tenant could not be retrieved from the request context

**Expected behavior**
The tenant ID ('tenant1') should be properly included in the gRPC request context/metadata when the worker is configured with tenant_ids=['tenant1'], allowing the worker to successfully activate jobs from that tenant.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS: M1 pro]
 - Browser [brave]
 - CamundaVersion [8.6]
- pyzeebeVersion [4.1.0]

**Additional context**
